[package]
name = "aoc-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
env_logger = "0.11.5"
log = "0.4"
clap = { version = "4.5.20", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["blocking"] }
